#!/usr/bin/env python3
"""Batch 56C — Upload reviewed Products/Brands media files to S3.

Reads the Batch 56C review CSV generated by backfill_s3_media_review_56c.py.
Uploads missing Products/Brands image files to S3 only. Does not update DynamoDB.

Default behavior:
- Include product + brand rows only.
- Upload rows where S3 Status = MISSING_IN_S3 and Local Match Status = FOUND.
- Skip Local Match Status = MISSING.
- Skip AMBIGUOUS rows unless record id is explicitly approved.
- For approved ambiguous rows, choose only if a safe single candidate can be resolved.
"""
from __future__ import annotations

import argparse
import csv
import mimetypes
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

import boto3
import botocore

DEFAULT_BUCKET = "rsa-cms-media-537765358118-ap-southeast-1"
DEFAULT_REVIEW_CSV = Path("docs/review/batch56c_products_brands_s3_backfill_review.csv")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Batch 56C Products/Brands S3 media backfill uploader.")
    parser.add_argument("--project-root", required=True, help="Project root folder, e.g. C:\\...\\cctv-crm-project")
    parser.add_argument("--review-csv", default=None, help="Review CSV path. Default: <project-root>/docs/review/batch56c_products_brands_s3_backfill_review.csv")
    parser.add_argument("--region", default=os.getenv("AWS_REGION") or os.getenv("AWS_DEFAULT_REGION") or "ap-southeast-1")
    parser.add_argument("--bucket", default=os.getenv("RSA_MEDIA_S3_BUCKET") or DEFAULT_BUCKET)
    parser.add_argument("--approved-ambiguous-record-id", action="append", default=["dlink"], help="Record ID allowed for safe ambiguous local-file resolution. Repeatable. Default: dlink")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--dry-run", action="store_true", help="Print actions only; upload nothing.")
    mode.add_argument("--execute", action="store_true", help="Upload approved missing files to S3.")
    return parser.parse_args()


def norm(value: Any) -> str:
    return str(value or "").strip()


def sanitize_token(value: str) -> str:
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "", value)
    return value


def split_candidates(value: str) -> List[Path]:
    if not value:
        return []
    return [Path(p.strip()) for p in value.split(" | ") if p.strip()]


def resolve_found_source(project_root: Path, row: Dict[str, str]) -> Optional[Path]:
    raw = norm(row.get("Matched Local Source Path"))
    if not raw:
        return None
    p = Path(raw)
    if not p.is_absolute():
        p = project_root / p
    return p if p.exists() and p.is_file() else None


def resolve_approved_ambiguous_source(project_root: Path, row: Dict[str, str], approved_ids: set[str]) -> Optional[Path]:
    record_id = norm(row.get("Record ID"))
    record_token = sanitize_token(record_id)
    if record_token not in approved_ids:
        return None

    candidates = split_candidates(norm(row.get("Matched Local Source Path")))
    candidates = [p if p.is_absolute() else project_root / p for p in candidates]
    candidates = [p for p in candidates if p.exists() and p.is_file()]

    if not candidates:
        return None

    # Safest first choice: exact current project path exists.
    current_project_path = norm(row.get("Current Project Path")).replace("\\", "/").lstrip("/")
    if current_project_path:
        exact = project_root / current_project_path
        exact_resolved = exact.resolve() if exact.exists() else None
        for p in candidates:
            try:
                if exact_resolved and p.resolve() == exact_resolved:
                    return p
            except OSError:
                pass

    # Next: prefer candidate whose filename or path clearly contains the approved record id token.
    token_matches = []
    for p in candidates:
        combined = sanitize_token(str(p))
        if record_token and record_token in combined:
            token_matches.append(p)
    if len(token_matches) == 1:
        return token_matches[0]

    # Next: prefer likely frontend static source folders over backups/review folders, only if unique.
    preferred = []
    for p in candidates:
        text = str(p).replace("\\", "/").lower()
        if any(part in text for part in ["/frontend/", "/assets/", "/brands/", "/images/"]):
            if not any(skip in text for skip in ["/.git/", "/docs/review/", "/backend/", "/venv/", "/node_modules/"]):
                preferred.append(p)
    if len(preferred) == 1:
        return preferred[0]

    print(f"SKIP_APPROVED_AMBIGUOUS_NEEDS_MANUAL record_id={record_id} candidates={len(candidates)}")
    for p in candidates:
        print(f"  CANDIDATE {p}")
    return None


def head_s3(s3: Any, bucket: str, key: str) -> str:
    try:
        s3.head_object(Bucket=bucket, Key=key)
        return "ALREADY_IN_S3"
    except botocore.exceptions.ClientError as exc:
        code = str(exc.response.get("Error", {}).get("Code", ""))
        if code in {"404", "NoSuchKey", "NotFound"}:
            return "MISSING_IN_S3"
        if code in {"403", "AccessDenied"}:
            return "S3_ACCESS_DENIED"
        return f"S3_ERROR_{code or 'UNKNOWN'}"


def upload_file(s3: Any, bucket: str, key: str, source: Path, content_type: str) -> None:
    extra_args = {
        "ContentType": content_type or mimetypes.guess_type(source.name)[0] or "application/octet-stream",
        "CacheControl": "public, max-age=3600",
    }
    s3.upload_file(str(source), bucket, key, ExtraArgs=extra_args)


def should_include_row(row: Dict[str, str]) -> bool:
    row_type = norm(row.get("Type")).lower()
    return row_type in {"product", "brand", "products", "brands"}


def main() -> int:
    args = parse_args()
    project_root = Path(args.project_root).resolve()
    review_csv = Path(args.review_csv) if args.review_csv else project_root / DEFAULT_REVIEW_CSV
    approved_ids = {sanitize_token(x) for x in args.approved_ambiguous_record_id if x}

    if not project_root.exists():
        print(f"ERROR project root does not exist: {project_root}", file=sys.stderr)
        return 2
    if not review_csv.exists():
        print(f"ERROR review CSV does not exist: {review_csv}", file=sys.stderr)
        print("Run backfill_s3_media_review_56c.py first.", file=sys.stderr)
        return 2

    mode = "EXECUTE" if args.execute else "DRY_RUN"
    print("Batch 56C Products/Brands S3 media backfill uploader")
    print(f"Mode: {mode}")
    print(f"Project root: {project_root}")
    print(f"Review CSV: {review_csv}")
    print(f"Region: {args.region}")
    print(f"Bucket: {args.bucket}")
    print(f"Approved ambiguous record IDs: {sorted(approved_ids)}")
    print("No DynamoDB records will be modified.")

    s3 = boto3.client("s3", region_name=args.region)

    counts = {
        "rows": 0,
        "included": 0,
        "would_upload": 0,
        "uploaded": 0,
        "already_in_s3": 0,
        "skip_missing": 0,
        "skip_ambiguous": 0,
        "skip_s3_status": 0,
        "skip_no_source": 0,
        "errors": 0,
    }

    with review_csv.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            counts["rows"] += 1
            if not should_include_row(row):
                continue
            counts["included"] += 1

            record_type = norm(row.get("Type"))
            record_id = norm(row.get("Record ID"))
            record_name = norm(row.get("Record Name"))
            s3_key = norm(row.get("S3 Key"))
            local_status = norm(row.get("Local Match Status")).upper()
            review_s3_status = norm(row.get("S3 Status")).upper()
            planned_action = norm(row.get("Planned Action"))

            if not s3_key:
                print(f"SKIP_NO_S3_KEY type={record_type} id={record_id} name={record_name}")
                counts["skip_s3_status"] += 1
                continue

            actual_s3_status = head_s3(s3, args.bucket, s3_key)
            if actual_s3_status == "ALREADY_IN_S3":
                print(f"ALREADY_IN_S3 type={record_type} id={record_id} key={s3_key}")
                counts["already_in_s3"] += 1
                continue
            if actual_s3_status != "MISSING_IN_S3":
                print(f"SKIP_S3_STATUS type={record_type} id={record_id} key={s3_key} status={actual_s3_status}")
                counts["skip_s3_status"] += 1
                continue

            source: Optional[Path] = None
            if local_status == "FOUND":
                source = resolve_found_source(project_root, row)
            elif local_status == "MISSING":
                print(f"SKIP_MISSING_LOCAL_FILE type={record_type} id={record_id} key={s3_key}")
                counts["skip_missing"] += 1
                continue
            elif local_status == "AMBIGUOUS":
                source = resolve_approved_ambiguous_source(project_root, row, approved_ids)
                if source is None:
                    print(f"SKIP_AMBIGUOUS type={record_type} id={record_id} key={s3_key}")
                    counts["skip_ambiguous"] += 1
                    continue
                print(f"APPROVED_AMBIGUOUS_MATCH type={record_type} id={record_id} source={source}")
            else:
                print(f"SKIP_LOCAL_STATUS type={record_type} id={record_id} key={s3_key} local_status={local_status}")
                counts["skip_no_source"] += 1
                continue

            if source is None or not source.exists() or not source.is_file():
                print(f"SKIP_NO_SOURCE_FILE type={record_type} id={record_id} key={s3_key} source={source}")
                counts["skip_no_source"] += 1
                continue

            content_type = norm(row.get("Content Type")) or mimetypes.guess_type(source.name)[0] or "application/octet-stream"
            size_kb = round(source.stat().st_size / 1024, 1)
            print(f"WOULD_UPLOAD type={record_type} id={record_id} action={planned_action} size_kb={size_kb} content_type={content_type}")
            print(f"  source={source}")
            print(f"  s3=s3://{args.bucket}/{s3_key}")
            counts["would_upload"] += 1

            if args.execute:
                try:
                    upload_file(s3, args.bucket, s3_key, source, content_type)
                    verify = head_s3(s3, args.bucket, s3_key)
                    if verify == "ALREADY_IN_S3":
                        print(f"UPLOADED_VERIFIED type={record_type} id={record_id} key={s3_key}")
                        counts["uploaded"] += 1
                    else:
                        print(f"ERROR_UPLOAD_NOT_VERIFIED type={record_type} id={record_id} key={s3_key} verify={verify}")
                        counts["errors"] += 1
                except Exception as exc:  # noqa: BLE001 - script should log and continue.
                    print(f"ERROR_UPLOAD_FAILED type={record_type} id={record_id} key={s3_key} error={exc}")
                    counts["errors"] += 1

    print("SUMMARY")
    for key, value in counts.items():
        print(f"{key}: {value}")
    print("No DynamoDB records modified.")
    if args.dry_run:
        print("Dry run only. Re-run with --execute after reviewing WOULD_UPLOAD lines.")
    return 1 if counts["errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
