#!/usr/bin/env python3
"""Batch 56C — Update Products/Brands DynamoDB image paths after S3 backfill.

Reads docs/review/batch56c_products_brands_s3_backfill_review.csv generated by
backfill_s3_media_review_56c.py.

Safety rules:
- Products + Brands only.
- Updates only rows where Current Project Path differs from To-be Project Path.
- To-be Project Path must start with /api/media/.
- S3 object for S3 Key must already exist.
- DynamoDB current value must still equal Current Project Path, unless --allow-current-mismatch is passed.
- Uses table key schema from DynamoDB and scans for the matching record ID.
- Dry run by default unless --execute is passed.
"""
from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

import boto3
import botocore
from boto3.dynamodb.conditions import Attr

DEFAULT_BUCKET = "rsa-cms-media-537765358118-ap-southeast-1"
DEFAULT_REVIEW_CSV = Path("docs/review/batch56c_products_brands_s3_backfill_review.csv")

ID_KEYS = {
    "product": ["product_id", "id", "product_key", "sku"],
    "products": ["product_id", "id", "product_key", "sku"],
    "brand": ["product_brand_key", "brand_key", "brand_id", "id"],
    "brands": ["product_brand_key", "brand_key", "brand_id", "id"],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Batch 56C DynamoDB media path updater for Products/Brands.")
    parser.add_argument("--project-root", required=True, help="Project root folder")
    parser.add_argument("--review-csv", default=None, help="Review CSV path. Default: <project-root>/docs/review/batch56c_products_brands_s3_backfill_review.csv")
    parser.add_argument("--region", default=os.getenv("AWS_REGION") or os.getenv("AWS_DEFAULT_REGION") or "ap-southeast-1")
    parser.add_argument("--bucket", default=os.getenv("RSA_MEDIA_S3_BUCKET") or DEFAULT_BUCKET)
    parser.add_argument("--allow-current-mismatch", action="store_true", help="Allow update even if DynamoDB current image path differs from review Current Project Path. Not recommended for first pass.")
    parser.add_argument("--out", default=None, help="Result CSV path. Default: <project-root>/docs/review/batch56c_dynamodb_media_path_update_results.csv")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--dry-run", action="store_true", help="Show planned updates only.")
    mode.add_argument("--execute", action="store_true", help="Apply approved updates.")
    return parser.parse_args()


def norm(value: Any) -> str:
    return str(value or "").strip()


def s3_exists(s3: Any, bucket: str, key: str) -> bool:
    try:
        s3.head_object(Bucket=bucket, Key=key)
        return True
    except botocore.exceptions.ClientError as exc:
        code = str(exc.response.get("Error", {}).get("Code", ""))
        if code in {"404", "NoSuchKey", "NotFound"}:
            return False
        raise


def key_schema_names(table: Any) -> List[str]:
    return [entry["AttributeName"] for entry in table.key_schema]


def make_item_key(table: Any, item: Dict[str, Any]) -> Dict[str, Any]:
    names = key_schema_names(table)
    missing = [name for name in names if name not in item]
    if missing:
        raise ValueError(f"Item missing key attributes: {missing}")
    return {name: item[name] for name in names}


def scan_for_record(table: Any, record_type: str, record_id: str) -> List[Dict[str, Any]]:
    candidates = ID_KEYS.get(record_type.lower(), [])
    if not candidates:
        return []

    # DynamoDB OR filter built from known ID attribute candidates.
    filt = None
    for attr_name in candidates:
        expr = Attr(attr_name).eq(record_id)
        filt = expr if filt is None else (filt | expr)

    items: List[Dict[str, Any]] = []
    kwargs: Dict[str, Any] = {"FilterExpression": filt}
    while True:
        response = table.scan(**kwargs)
        items.extend(response.get("Items", []))
        last_key = response.get("LastEvaluatedKey")
        if not last_key:
            break
        kwargs["ExclusiveStartKey"] = last_key
    return items


def choose_matching_item(items: List[Dict[str, Any]], image_field: str, current_path: str) -> Optional[Dict[str, Any]]:
    exact = [item for item in items if norm(item.get(image_field)) == current_path]
    if len(exact) == 1:
        return exact[0]
    if len(items) == 1:
        return items[0]
    return None


def include_row(row: Dict[str, str]) -> bool:
    row_type = norm(row.get("Type")).lower()
    if row_type not in {"product", "products", "brand", "brands"}:
        return False
    current_path = norm(row.get("Current Project Path"))
    to_be_path = norm(row.get("To-be Project Path"))
    s3_key = norm(row.get("S3 Key"))
    if not current_path or not to_be_path or not s3_key:
        return False
    if current_path == to_be_path:
        return False
    if not to_be_path.startswith("/api/media/"):
        return False
    return True


def main() -> int:
    args = parse_args()
    project_root = Path(args.project_root).resolve()
    review_csv = Path(args.review_csv) if args.review_csv else project_root / DEFAULT_REVIEW_CSV
    out_csv = Path(args.out) if args.out else project_root / "docs" / "review" / "batch56c_dynamodb_media_path_update_results.csv"
    out_csv.parent.mkdir(parents=True, exist_ok=True)

    if not review_csv.exists():
        print(f"ERROR review CSV not found: {review_csv}", file=sys.stderr)
        return 2

    mode = "EXECUTE" if args.execute else "DRY_RUN"
    print("Batch 56C DynamoDB Products/Brands media path updater")
    print(f"Mode: {mode}")
    print(f"Project root: {project_root}")
    print(f"Review CSV: {review_csv}")
    print(f"Region: {args.region}")
    print(f"Bucket: {args.bucket}")
    print(f"Allow current mismatch: {args.allow_current_mismatch}")

    ddb = boto3.resource("dynamodb", region_name=args.region)
    s3 = boto3.client("s3", region_name=args.region)

    counts = {
        "rows": 0,
        "candidate_updates": 0,
        "would_update": 0,
        "updated": 0,
        "skipped_same_path": 0,
        "skipped_missing_s3": 0,
        "skipped_not_found": 0,
        "skipped_ambiguous": 0,
        "skipped_current_mismatch": 0,
        "errors": 0,
    }
    results: List[Dict[str, Any]] = []

    with review_csv.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            counts["rows"] += 1
            if not include_row(row):
                if norm(row.get("Current Project Path")) == norm(row.get("To-be Project Path")):
                    counts["skipped_same_path"] += 1
                continue

            counts["candidate_updates"] += 1
            row_type = norm(row.get("Type")).lower()
            record_id = norm(row.get("Record ID"))
            record_name = norm(row.get("Record Name"))
            table_name = norm(row.get("DynamoDB Table"))
            image_field = norm(row.get("Image Field"))
            current_path = norm(row.get("Current Project Path"))
            to_be_path = norm(row.get("To-be Project Path"))
            s3_key = norm(row.get("S3 Key"))

            result = {
                "Type": row_type,
                "Record ID": record_id,
                "Record Name": record_name,
                "DynamoDB Table": table_name,
                "Image Field": image_field,
                "Current Project Path": current_path,
                "To-be Project Path": to_be_path,
                "S3 Key": s3_key,
                "Result": "",
                "Notes": "",
            }

            try:
                if not s3_exists(s3, args.bucket, s3_key):
                    print(f"SKIP_MISSING_S3 type={row_type} id={record_id} key={s3_key}")
                    counts["skipped_missing_s3"] += 1
                    result["Result"] = "SKIP_MISSING_S3"
                    results.append(result)
                    continue

                table = ddb.Table(table_name)
                matches = scan_for_record(table, row_type, record_id)
                if not matches:
                    print(f"SKIP_RECORD_NOT_FOUND type={row_type} id={record_id} table={table_name}")
                    counts["skipped_not_found"] += 1
                    result["Result"] = "SKIP_RECORD_NOT_FOUND"
                    results.append(result)
                    continue

                item = choose_matching_item(matches, image_field, current_path)
                if item is None:
                    print(f"SKIP_AMBIGUOUS_RECORD type={row_type} id={record_id} matches={len(matches)} field={image_field}")
                    counts["skipped_ambiguous"] += 1
                    result["Result"] = "SKIP_AMBIGUOUS_RECORD"
                    result["Notes"] = f"matches={len(matches)}"
                    results.append(result)
                    continue

                actual_current = norm(item.get(image_field))
                if actual_current != current_path and not args.allow_current_mismatch:
                    print(f"SKIP_CURRENT_MISMATCH type={row_type} id={record_id}")
                    print(f"  review_current={current_path}")
                    print(f"  dynamodb_current={actual_current}")
                    counts["skipped_current_mismatch"] += 1
                    result["Result"] = "SKIP_CURRENT_MISMATCH"
                    result["Notes"] = f"dynamodb_current={actual_current}"
                    results.append(result)
                    continue

                key = make_item_key(table, item)
                print(f"WOULD_UPDATE type={row_type} id={record_id} table={table_name} field={image_field}")
                print(f"  from={actual_current}")
                print(f"  to={to_be_path}")
                counts["would_update"] += 1

                if args.execute:
                    expr_names = {"#field": image_field}
                    expr_values = {":new": to_be_path}
                    kwargs = {
                        "Key": key,
                        "UpdateExpression": "SET #field = :new",
                        "ExpressionAttributeNames": expr_names,
                        "ExpressionAttributeValues": expr_values,
                        "ReturnValues": "UPDATED_NEW",
                    }
                    if not args.allow_current_mismatch:
                        expr_values[":old"] = current_path
                        kwargs["ConditionExpression"] = "#field = :old"
                    table.update_item(**kwargs)
                    print(f"UPDATED type={row_type} id={record_id} field={image_field}")
                    counts["updated"] += 1
                    result["Result"] = "UPDATED"
                else:
                    result["Result"] = "WOULD_UPDATE"
                results.append(result)
            except Exception as exc:  # noqa: BLE001 - closeout script should log and continue.
                print(f"ERROR type={row_type} id={record_id} error={exc}")
                counts["errors"] += 1
                result["Result"] = "ERROR"
                result["Notes"] = str(exc)
                results.append(result)

    with out_csv.open("w", encoding="utf-8-sig", newline="") as f:
        fieldnames = [
            "Type", "Record ID", "Record Name", "DynamoDB Table", "Image Field",
            "Current Project Path", "To-be Project Path", "S3 Key", "Result", "Notes",
        ]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)

    print("SUMMARY")
    for key, value in counts.items():
        print(f"{key}: {value}")
    print(f"Results CSV: {out_csv}")
    if args.dry_run:
        print("Dry run only. Re-run with --execute if WOULD_UPDATE rows look correct.")
    return 1 if counts["errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
